Test for bud / tag:
jshiftio/buildah-java pull request #8
Opened 2020-01-22 08:46 UTC by naude-r

- add a test for bud --build-arg
- add a test for buildah tag

2020-01-22 09:28 UTC, naude-r commented
@rohanKanojia tests cases for:
- bud --build-arg
- tag command

2020-01-23 14:30 UTC, naude-r commented
@rohanKanojia would it be possible to make a new release?

2020-01-23 14:44 UTC, rohanKanojia commented
@naude-r :Sure, I'll try to cut a release sometime tomorrow

2020-01-23 17:18 UTC, manusa commented on buildah-core/src/test/java/io/jshift/buildah/core/commands/BudCommandTest.java
> +        Map<String, String> buildArgs = new HashMap<>();
Should be possible to replace by:
`Map<String, String> buildArgs = Collections.singletonMap("TEST", "TEST_VAL");

2020-01-23 17:18 UTC, manusa commented on buildah-core/src/test/java/io/jshift/buildah/core/commands/BudCommandTest.java
> +        List<String> dockerfileList = new ArrayList<>();
Should be possible to replace by:
`List<String> dockerfileList = Collections.singletonList("Dockerfile");

2020-01-23 17:20 UTC, manusa commented on buildah-core/src/test/java/io/jshift/buildah/core/commands/TagCommandTest.java
> +        List<String> tags = new ArrayList<>();
Should be possible to replace by:
`List<String> tags = Arrays.asList("latest", "v1.0.0");`

2020-01-23 17:21 UTC, manusa requested changes
Please check comments and squash your changes in a single commit

2020-01-24 06:42 UTC, naude-r commented
> Please check comments and squash your changes in a single commit

comments addressed. have an issue when attempting to squash the commits. any hints?

2020-01-24 06:53 UTC, naude-r commented
> > Please check comments and squash your changes in a single commit
> 
> comments addressed. have an issue when attempting to squash the commits. any hints?

nevermind. got it working....

2020-01-24 07:03 UTC, manusa approved these changes
LGTM, thanks for your contribution! :wink:

2020-01-24 07:41 UTC, rohanKanojia approved these changes

2020-01-24 07:41 UTC, merged

2020-01-24 09:29 UTC, rohanKanojia commented
@naude-r: I've released 1.0.1 which contains this fix

2020-01-24 09:33 UTC, naude-r commented
@rohanKanojia Thank you!. Working just fine.